# Generated by Django 4.2.4 on 2023-09-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='senior_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('suffix', models.CharField(max_length=5, null=True)),
                ('age', models.BigIntegerField(null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('OSCA_ID', models.CharField(max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
