# Generated by Django 4.2.4 on 2023-11-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_list',
            name='claimed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senior_list',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
