# Generated by Django 4.2.7 on 2023-11-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_senior_list_claimed_date_senior_list_is_claimed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example',
        ),
    ]
