# Generated by Django 4.2.7 on 2023-11-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_senior_list_senior_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_list',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
