# Generated by Django 4.2.7 on 2023-11-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_senior_list_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior_list',
            name='senior_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
